# Theoritical results

__Exercice 3.1__ 
Demonstrate that the matrix of scalar products can be derived from the distance matrix via double-centering, in the case of Euclidean distance.

Given $\mathbf{x}_1, ..., \mathbf{x}_n \in \mathbb{R}^m$, we define the squared distance matrix $D = [d_{ij}^2]_{ij} \in \mathbb{R}^{n \times n}$ where $d_{ij}^2 = ||\mathbf{x}_i - \mathbf{x}_j||_2^2$ and the Gram matrix $G = [g_{ij}]_{ij} \in \mathbb{R}^{n \times n}$ where $g_{ij} = x_i^Tx_j$. We suppose, without loss of generality, that $\mathbf{x}_i$ are mean-centered, i.e. $\sum_i \mathbf{x}_i = 0$. 
We want to prove that the Gram matrix $G$ can be computed from the squared distance matrix $D$ via double-centering. It is a way of transforming a rectangular matrix to the one having mean values of rows equal to zero and mean values of columns equal to zero, by multiplying the centering matrix $C = I_n - \frac{1}{n}\mathbf{1}^T\mathbf{1}$ to both sides of D.

In other words, we want to find a constant $\alpha$ such that $G = \alpha CDC$.

In [2]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances

In [4]:
m = 3
n = 2

X = np.random.rand(m,n) # Data

centering_matrix = lambda n: np.identity(n) - np.ones((n,n))/n
centered_X = X @ centering_matrix(n)

distance_matrix = euclidean_distances(X.T)**2
distance_matrix_from_centered = euclidean_distances(centered_X.T)**2

actual_gram_matrix = centered_X.T @ centered_X
uncentered_gram_matrix = X.T @ X
centered_gram_matrix = centering_matrix(n).T @ distance_matrix_from_centered @ centering_matrix(n)

In [5]:
actual_gram_matrix

array([[ 0.02384575, -0.02384575],
       [-0.02384575,  0.02384575]])

In [6]:
centered_gram_matrix

array([[-0.04769151,  0.04769151],
       [ 0.04769151, -0.04769151]])

In [7]:
np.divide(actual_gram_matrix, centered_gram_matrix)

array([[-0.5, -0.5],
       [-0.5, -0.5]])